# Week 3 – Feature Engineering on the Updated Retail Dataset

## Project
**Demand Forecasting for Retail Inventory Optimization**

## Objective

In this section, we explore four text vectorization methods:

1. **Bag of Words (BoW)**
2. **TF-IDF**
3. **Word2Vec**
4. **BERT / Transformer Embeddings**

These methods convert text-like fields into numerical vectors that can later be combined with structured retail features for machine learning models.

## Important Note

The updated retail dataset is primarily a **structured tabular dataset**.  
The text-like fields in this dataset are mostly **short categorical/business labels** such as:

- `Category`
- `Store_Type`
- `Festival_Name`
- `Festival_Type`
- `Product_Name`
- `Sub_Category`
- `Brand_Name`
- `Brand_Tier`
- `Promotion_Type`

Therefore, these vectorization methods are being explored as part of the project requirement, but they are **not the primary feature engineering strategy** for this dataset.  
Later, we will also apply more appropriate tabular feature engineering methods.

## Target Variable

The target variable remains:

`Daily_Units_Sold`

In [1]:
import numpy as np
import pandas as pd
import scipy
import sklearn
import gensim

print("numpy:", np.__version__)
print("pandas:", pd.__version__)
print("scipy:", scipy.__version__)
print("sklearn:", sklearn.__version__)
print("gensim:", gensim.__version__)

numpy: 1.26.4
pandas: 2.2.2
scipy: 1.13.1
sklearn: 1.6.1
gensim: 4.3.3

In [2]:
# @title Import basic libraries for data handling
#import pandas as pd
#import numpy as np

# Import libraries for text processing
import re
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# Import libraries for Word2Vec
from gensim.models import Word2Vec

# Import library for contextual embeddings
!pip -q install sentence-transformers

from sentence_transformers import SentenceTransformer

# Display options for readability
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 120)

/usr/local/lib/python3.12/dist-packages/sentence_transformers/cross_encoder/CrossEncoder.py:11: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange
WARNING:torchao.kernel.intmm:Warning: Detected no triton, on systems without Triton certain kernels will not work

## Load the Updated Dataset

We first load the updated retail dataset and inspect its shape and column names.

The updated dataset is expected to contain:
- 2,000 rows
- 58 columns

In [3]:
# @title Load the updated dataset
df = pd.read_csv("/content/master_retail_dataset_v2.csv")

# Display shape of the dataset
print("Dataset shape:", df.shape)

# Preview first 5 rows
df.head()

Dataset shape: (2000, 58)

,Date,DayOfWeek,Month,Year,Is_Weekend,Is_Holiday,Product_ID,Category,Base_Price,Discount_Percentage,Current_Price,Store_ID,Store_Type,Competitor_Price,Footfall_Index,Avg_Temperature,Rainfall_mm,Social_Media_Sentiment,Lead_Time_Days,Safety_Stock_Level,Stock_On_Hand,Daily_Units_Sold,Festival_Name,Festival_Type,UPC_EAN,Product_Name,Sub_Category,Brand_Name,Brand_Tier,Shelf_Life_Days,No_of_Checkout_Counters,Avg_Billing_Time_min,Local_Population_Density,Product_Age_Days,No_of_Customer_Purchases,Unit_Cost,Promotional_Campaign_Flag,Competitor_Promotion_Flag,Google_Trends_Current_Wk,Google_Trends_Lag_1w,Shelf_Capacity,Promotion_Type,Marketing_Spend,Payday_Flag,School_Vacation_Flag,Local_Event_Flag,Launch_Date,Seasonal_Product_Flag,Online_Sales_Units,In_Store_Sales_Units,App_Traffic_Index,Website_Visits,Backorder_Flag,Supplier_Delay_Days,Fill_Rate_Pct,Loyalty_Program_Usage_Count,Repeat_Purchase_Rate,Avg_Basket_Size
0,04/13/2023,3,4,2023,0,0,1002,Grocery,410.09,0.01,405.99,15,Urban,411.58,127.6,29.1,8.5,0.63,7,141,471,83,NaN,NaN,8148570840155,Nestle Beverages 1002,Beverages,Nestle,Premium,54,6,5.9,12371,228,22,322.20,N,N,32,32,30,NaN,1247,0,0,0,08/28/2022,Y,12,71,488,896,N,0,88.93,11,0.14,3.77
1,12/15/2023,4,12,2023,0,0,1014,Home,89.98,0.30,62.99,7,Rural,90.37,56.9,1.9,5.3,0.35,11,59,263,102,NaN,NaN,7203826864190,Tupperware Decor 1014,Decor,Tupperware,Budget,2244,11,5.2,1046,1822,69,47.96,Y,Y,77,32,99,Flash Sale,1942,0,1,0,12/19/2018,Y,31,71,619,1406,N,2,90.16,31,0.14,1.48
2,09/28/2023,3,9,2023,0,0,1015,Electronics,404.88,0.14,348.20,17,Urban,408.07,191.8,14.5,2.8,0.77,4,111,302,89,NaN,NaN,5094762337870,Sony Computers 1015,Computers,Sony,Mid,1196,11,7.4,9278,1759,83,319.44,N,Y,19,77,71,NaN,1042,0,0,0,12/04/2018,N,32,57,626,1432,N,6,88.00,23,0.38,1.07
3,04/17/2023,0,4,2023,0,0,1012,Grocery,347.97,0.43,198.34,12,Urban,349.20,71.6,24.4,1.3,0.86,11,38,389,98,NaN,NaN,16104203210,Nestle Spices 1012,Spices,Nestle,Premium,7,8,4.4,7650,1330,21,266.76,Y,N,33,19,28,Flash Sale,4105,0,0,0,08/26/2019,N,32,66,626,1432,N,2,91.17,7,0.13,4.67
4,03/13/2023,0,3,2023,0,0,1016,Grocery,280.16,0.14,240.94,18,Urban,252.64,185.5,26.0,0.4,0.36,14,46,262,100,NaN,NaN,8572879201082,Tata Spices 1016,Spices,Tata,Premium,10,13,2.6,5779,1127,46,172.32,N,Y,60,33,95,NaN,706,0,0,0,02/10/2020,N,23,77,564,1191,N,0,89.39,9,0.16,2.17

## Identify Text-Like Features

The dataset is mostly structured, but some fields contain business labels that can be treated as text-like features for vectorization.

The selected columns are:

- `Category`
- `Store_Type`
- `Festival_Name`
- `Festival_Type`
- `Product_Name`
- `Sub_Category`
- `Brand_Name`
- `Brand_Tier`
- `Promotion_Type`

In [4]:
# @title List of text-like columns selected for vectorization
text_columns = [
    "Category",
    "Store_Type",
    "Festival_Name",
    "Festival_Type",
    "Product_Name",
    "Sub_Category",
    "Brand_Name",
    "Brand_Tier",
    "Promotion_Type"
]

# Show number of unique values in each selected text column
for col in text_columns:
    print(f"{col}: {df[col].nunique()} unique values")

Category: 5 unique values
Store_Type: 2 unique values
Festival_Name: 8 unique values
Festival_Type: 3 unique values
Product_Name: 100 unique values
Sub_Category: 20 unique values
Brand_Name: 19 unique values
Brand_Tier: 3 unique values
Promotion_Type: 4 unique values

## Create a Combined Text Field

Most vectorization methods work on a single text document per row.

To apply these methods, we combine the selected text-like columns into one consolidated text field called:

`combined_text`

This creates a simple text representation of each retail record.

In [5]:
# Fill missing values with empty string just in case
df[text_columns] = df[text_columns].fillna("")

# Combine selected columns into one text string per row
df["combined_text"] = df[text_columns].astype(str).agg(" ".join, axis=1)

# Preview the combined text
df[["combined_text"]].head()

                                                           combined_text
0        Grocery Urban   Nestle Beverages 1002 Beverages Nestle Premium
1  Home Rural   Tupperware Decor 1014 Decor Tupperware Budget Flash Sale
2            Electronics Urban   Sony Computers 1015 Computers Sony Mid
3    Grocery Urban   Nestle Spices 1012 Spices Nestle Premium Flash Sale
4                  Grocery Urban   Tata Spices 1016 Spices Tata Premium

## Basic Text Cleaning

Before vectorization, we perform light text cleaning:

- convert text to lowercase
- remove extra spaces
- keep only letters, numbers, and spaces

This is a simple preprocessing step suitable for the current dataset.

In [6]:
# Function to clean text
def clean_text(text):
    """
    Clean input text by:
    1. converting to lowercase
    2. removing special characters
    3. removing extra spaces
    """
    text = text.lower()
    text = re.sub(r"[^a-zA-Z0-9\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

# Apply cleaning
df["clean_text"] = df["combined_text"].apply(clean_text)

# Preview cleaned text
df[["combined_text", "clean_text"]].head()

,combined_text,clean_text
0,Grocery Urban Nestle Beverages 1002 Beverages Nestle Premium,grocery urban nestle beverages 1002 beverages nestle premium
1,Home Rural Tupperware Decor 1014 Decor Tupperware Budget Flash Sale,home rural tupperware decor 1014 decor tupperware budget flash sale
2,Electronics Urban Sony Computers 1015 Computers Sony Mid,electronics urban sony computers 1015 computers sony mid
3,Grocery Urban Nestle Spices 1012 Spices Nestle Premium Flash Sale,grocery urban nestle spices 1012 spices nestle premium flash sale
4,Grocery Urban Tata Spices 1016 Spices Tata Premium,grocery urban tata spices 1016 spices tata premium

# 1. Bag of Words (BoW)

## Concept

Bag of Words converts each document into a vector of **word counts**.

If a word appears more often in a row's text, its value in the vector is higher.

### Formula

For document $d_i$ and term $w_j$:

$
x_{ij} = \text{count}(w_j, d_i)
$

where:
- $x_{ij}$ = count of word $w_j$ in document $d_i$

## Why We Are Using It

BoW is:
- simple
- easy to interpret
- useful as a baseline vectorization method

## Limitation

It does **not** capture:
- semantic meaning
- word order
- context

In [7]:
# Create a CountVectorizer object
# max_features limits the vocabulary size so the matrix remains manageable
bow_vectorizer = CountVectorizer(max_features=100)

# Learn vocabulary and transform text into count vectors
X_bow = bow_vectorizer.fit_transform(df["clean_text"])

# Convert sparse matrix to DataFrame for inspection
bow_df = pd.DataFrame(
    X_bow.toarray(),
    columns=bow_vectorizer.get_feature_names_out()
)

print("BoW matrix shape:", bow_df.shape)
bow_df.head()

BoW matrix shape: (2000, 95)

,1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019,accessories,activewear,allen,amul,ashirvad,audio,beauty,bedding,beverages,bogo,bose,budget,christmas,clothing,computers,dairy,day,decor,dhanteras,discount,diwali,dove,dussehra,eid,electronics,ethnic,fabindia,festive,fitr,flash,formalwear,fragrance,furniture,gifting,grains,grocery,haircare,holi,home,ikea,independence,kitchenware,lakme,levis,loyalty,makeup,mega,mid,mobiles,nestle,new,nivea,only,oreal,philips,premium,rural,sale,samsung,season,seasonal,skincare,sleepwell,solly,sony,spices,tata,tupperware,ul,urban,wear,wedding,winter,year,zara
0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,1,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,2,0,0,0,1,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,2,2,0,0,1,0,0,0,0,0

## Observation

Bag of Words produced a **2000 × 95** sparse feature matrix. Although the vectorizer was configured with `max_features=100`, the effective vocabulary extracted from the cleaned combined text was **95 tokens**.

The generated vocabulary is dominated by:
- short business labels such as categories, brand tiers, and promotion words
- product/store identifiers such as `1002`, `1014`, and similar numeric tokens
- repeated business terms such as product or sub-category names

This confirms that BoW is mainly capturing **token presence and repetition** in structured label-style text rather than rich natural language context. For this dataset, it works as a simple baseline representation, but it mostly reflects category, brand, promotion, and identifier information.

## Note on Combined Text Representation

In the Bag of Words approach, all selected text-like columns were combined into a single document per row.

This is a standard NLP baseline approach, but it may mix semantically different fields such as:
- product
- brand
- store type
- promotion
- festival

This limitation is examined further in the next section.

# 2. TF-IDF

## Concept

TF-IDF stands for **Term Frequency – Inverse Document Frequency**.

It improves upon Bag of Words by giving:
- higher weight to words that are important in a specific document
- lower weight to very common words across many documents

### Formula

$
\text{TF-IDF}(t, d) = \text{TF}(t, d) \times \text{IDF}(t)
$

where:

$
\text{IDF}(t) = \log\left(\frac{N}{df(t)}\right)
$

- $N$ = total number of documents
- $df(t)$ = number of documents containing term $t$

## Why We Are Using It

TF-IDF is useful because it highlights **informative terms** and reduces the impact of overly common words.

## Limitation

It still does not capture semantic meaning or context.

In [8]:
# Create TF-IDF vectorizer
tfidf_vectorizer = TfidfVectorizer(max_features=100)

# Fit and transform the cleaned text
X_tfidf = tfidf_vectorizer.fit_transform(df["clean_text"])

# Convert sparse matrix to DataFrame for inspection
tfidf_df = pd.DataFrame(
    X_tfidf.toarray(),
    columns=tfidf_vectorizer.get_feature_names_out()
)

print("TF-IDF matrix shape:", tfidf_df.shape)
tfidf_df.head()

TF-IDF matrix shape: (2000, 95)

,1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019,accessories,activewear,allen,amul,ashirvad,audio,beauty,bedding,beverages,bogo,bose,budget,christmas,clothing,computers,dairy,day,decor,dhanteras,discount,diwali,dove,dussehra,eid,electronics,ethnic,fabindia,festive,fitr,flash,formalwear,fragrance,furniture,gifting,grains,grocery,haircare,holi,home,ikea,independence,kitchenware,lakme,levis,loyalty,makeup,mega,mid,mobiles,nestle,new,nivea,only,oreal,philips,premium,rural,sale,samsung,season,seasonal,skincare,sleepwell,solly,sony,spices,tata,tupperware,ul,urban,wear,wedding,winter,year,zara
0,0.0,0.0,0.327848,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.641556,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.205741,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.628539,0.0,0.0,0.0,0.0,0.0,0.168795,0.00000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.122632,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.301024,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.165315,0.0,0.0,0.000000,0.0,0.0,0.640908,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.208649,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.204371,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.15071,0.208649,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.565457,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.339328,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.585307,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.231802,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.185165,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.661084,0.000000,0.000000,0.000000,0.0,0.131229,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.316718,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.222987,0.0,0.0,0.0,0.0,0.0,0.208258,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.636228,0.0,0.0,0.0,0.0,0.0,0.170860,0.00000,0.222987,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.554513,0.000000,0.000000,0.0,0.124132,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.338691,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.220248,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.180697,0.00000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.586439,0.665569,0.000000,0.0,0.131279,0.0,0.0,0.0,0.0,0.0

## Observation

TF-IDF produced a **2000 × 95** weighted feature matrix, which matches the effective vocabulary size observed in the Bag of Words representation.

Compared with BoW, TF-IDF assigns higher weight to terms that are more specific to individual records and lower weight to terms that appear very frequently across many rows. In this dataset, the weighting is especially useful because the combined text contains repeated business labels such as category, brand, and promotion terms.

However, the output also shows that many important tokens are still short structured labels or numeric identifiers rather than descriptive sentences. Therefore, TF-IDF is more informative than BoW for highlighting distinguishing labels, but it is still limited by the short, categorical nature of the text fields.

## Limitation of Combined Text TF-IDF

The previous TF-IDF approach treated all text-like columns as one combined document per row.

However, this dataset contains multiple text-like fields with different meanings, such as:

- `Category`
- `Store_Type`
- `Festival_Name`
- `Festival_Type`
- `Product_Name`
- `Sub_Category`
- `Brand_Name`
- `Brand_Tier`
- `Promotion_Type`

Combining them into a single text string mixes unrelated semantic categories. As a result, the TF-IDF representation may lose interpretability because words from different business domains are treated as if they belong to the same context.

## Improved Approach: Column-wise TF-IDF Vectorization

To preserve the semantic meaning of each text-like feature, TF-IDF can be applied separately to each column rather than combining all columns into one document.

This approach helps to:

- preserve feature-specific context
- reduce semantic mixing
- improve interpretability

In this method, each text column is vectorized independently, and the resulting feature matrices are then concatenated.

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Create an empty list to store TF-IDF DataFrames for each column
tfidf_features = []

# Apply TF-IDF separately to each text column
for col in text_columns:
    # Initialize TF-IDF vectorizer
    # max_features is limited to keep the feature space manageable
    vectorizer = TfidfVectorizer(max_features=20)

    # Convert the current column to string
    text_data = df[col].astype(str)

    # Fit and transform the column
    col_matrix = vectorizer.fit_transform(text_data)

    # Convert sparse matrix to DataFrame
    col_df = pd.DataFrame(
        col_matrix.toarray(),
        columns=[f"{col}_{word}" for word in vectorizer.get_feature_names_out()]
    )

    # Store the result
    tfidf_features.append(col_df)

# Combine all column-wise TF-IDF features into one DataFrame
tfidf_combined_df = pd.concat(tfidf_features, axis=1)

# Display shape and preview
print("Column-wise TF-IDF shape:", tfidf_combined_df.shape)
tfidf_combined_df.head()

Column-wise TF-IDF shape: (2000, 94)

,Category_beauty,Category_clothing,Category_electronics,Category_grocery,Category_home,Store_Type_rural,Store_Type_urban,Festival_Name_christmas,Festival_Name_day,Festival_Name_dhanteras,Festival_Name_diwali,Festival_Name_dussehra,Festival_Name_eid,Festival_Name_fitr,Festival_Name_holi,Festival_Name_independence,Festival_Name_new,Festival_Name_ul,Festival_Name_year,Festival_Type_festive,Festival_Type_gifting,Festival_Type_mega,Festival_Type_season,Festival_Type_wedding,Product_Name_1012,Product_Name_1014,Product_Name_1015,Product_Name_1016,Product_Name_1019,Product_Name_activewear,Product_Name_ashirvad,Product_Name_computers,Product_Name_fabindia,Product_Name_fragrance,Product_Name_kitchenware,Product_Name_lakme,Product_Name_makeup,Product_Name_nestle,Product_Name_samsung,Product_Name_sony,Product_Name_spices,Product_Name_tata,Product_Name_tupperware,Product_Name_wear,Sub_Category_accessories,Sub_Category_activewear,Sub_Category_audio,Sub_Category_bedding,Sub_Category_beverages,Sub_Category_computers,Sub_Category_decor,Sub_Category_ethnic,Sub_Category_formalwear,Sub_Category_fragrance,Sub_Category_furniture,Sub_Category_grains,Sub_Category_haircare,Sub_Category_kitchenware,Sub_Category_makeup,Sub_Category_mobiles,Sub_Category_skincare,Sub_Category_spices,Sub_Category_wear,Sub_Category_winter,Brand_Name_allen,Brand_Name_amul,Brand_Name_ashirvad,Brand_Name_bose,Brand_Name_dove,Brand_Name_fabindia,Brand_Name_ikea,Brand_Name_lakme,Brand_Name_levis,Brand_Name_nestle,Brand_Name_nivea,Brand_Name_oreal,Brand_Name_philips,Brand_Name_samsung,Brand_Name_sleepwell,Brand_Name_solly,Brand_Name_sony,Brand_Name_tata,Brand_Name_tupperware,Brand_Name_zara,Brand_Tier_budget,Brand_Tier_mid,Brand_Tier_premium,Promotion_Type_bogo,Promotion_Type_discount,Promotion_Type_flash,Promotion_Type_loyalty,Promotion_Type_only,Promotion_Type_sale,Promotion_Type_seasonal
0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,1.000000,0.0,0.000000,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
1,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.728911,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.00000,0.684609,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.707107,0.0,0.0,0.707107,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.609405,0.000000,0.0,0.0,0.0,0.525581,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.593625,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.600282,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.602928,0.0,0.000000,0.525490,0.00000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.707107,0.0,0.0,0.707107,0.0
4,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.606904,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.525423,0.59632,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0

## Observation

The column-wise TF-IDF approach preserves the semantic role of each feature by vectorizing each column independently.

Compared to the combined-text TF-IDF approach:

- semantic mixing is reduced
- feature meaning is preserved more clearly
- interpretability is improved

This makes the representation more suitable for structured datasets in which different text columns represent different business concepts.

However, these fields are still short categorical labels rather than natural language text. Therefore, although column-wise TF-IDF is an improvement over combined-text TF-IDF, traditional categorical encoding methods such as one-hot encoding and frequency encoding remain more appropriate for this dataset.

## Prepare Tokens for Word2Vec

Word2Vec requires tokenized text input.

So we convert each cleaned text row into a list of words.

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Create an empty list to store TF-IDF DataFrames for each column
tfidf_features = []

# Apply TF-IDF separately to each text column
for col in text_columns:
    # Initialize TF-IDF vectorizer
    # max_features is limited to keep the feature space manageable
    vectorizer = TfidfVectorizer(max_features=20)

    # Convert the current column to string
    text_data = df[col].astype(str)

    # Fit and transform the column
    col_matrix = vectorizer.fit_transform(text_data)

    # Convert sparse matrix to DataFrame
    col_df = pd.DataFrame(
        col_matrix.toarray(),
        columns=[f"{col}_{word}" for word in vectorizer.get_feature_names_out()]
    )

    # Store the result
    tfidf_features.append(col_df)

# Combine all column-wise TF-IDF features into one DataFrame
tfidf_combined_df = pd.concat(tfidf_features, axis=1)

# Display shape and preview
print("Column-wise TF-IDF shape:", tfidf_combined_df.shape)
tfidf_combined_df.head()

Column-wise TF-IDF shape: (2000, 94)

,Category_beauty,Category_clothing,Category_electronics,Category_grocery,Category_home,Store_Type_rural,Store_Type_urban,Festival_Name_christmas,Festival_Name_day,Festival_Name_dhanteras,Festival_Name_diwali,Festival_Name_dussehra,Festival_Name_eid,Festival_Name_fitr,Festival_Name_holi,Festival_Name_independence,Festival_Name_new,Festival_Name_ul,Festival_Name_year,Festival_Type_festive,Festival_Type_gifting,Festival_Type_mega,Festival_Type_season,Festival_Type_wedding,Product_Name_1012,Product_Name_1014,Product_Name_1015,Product_Name_1016,Product_Name_1019,Product_Name_activewear,Product_Name_ashirvad,Product_Name_computers,Product_Name_fabindia,Product_Name_fragrance,Product_Name_kitchenware,Product_Name_lakme,Product_Name_makeup,Product_Name_nestle,Product_Name_samsung,Product_Name_sony,Product_Name_spices,Product_Name_tata,Product_Name_tupperware,Product_Name_wear,Sub_Category_accessories,Sub_Category_activewear,Sub_Category_audio,Sub_Category_bedding,Sub_Category_beverages,Sub_Category_computers,Sub_Category_decor,Sub_Category_ethnic,Sub_Category_formalwear,Sub_Category_fragrance,Sub_Category_furniture,Sub_Category_grains,Sub_Category_haircare,Sub_Category_kitchenware,Sub_Category_makeup,Sub_Category_mobiles,Sub_Category_skincare,Sub_Category_spices,Sub_Category_wear,Sub_Category_winter,Brand_Name_allen,Brand_Name_amul,Brand_Name_ashirvad,Brand_Name_bose,Brand_Name_dove,Brand_Name_fabindia,Brand_Name_ikea,Brand_Name_lakme,Brand_Name_levis,Brand_Name_nestle,Brand_Name_nivea,Brand_Name_oreal,Brand_Name_philips,Brand_Name_samsung,Brand_Name_sleepwell,Brand_Name_solly,Brand_Name_sony,Brand_Name_tata,Brand_Name_tupperware,Brand_Name_zara,Brand_Tier_budget,Brand_Tier_mid,Brand_Tier_premium,Promotion_Type_bogo,Promotion_Type_discount,Promotion_Type_flash,Promotion_Type_loyalty,Promotion_Type_only,Promotion_Type_sale,Promotion_Type_seasonal
0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,1.000000,0.0,0.000000,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
1,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.728911,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.00000,0.684609,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.707107,0.0,0.0,0.707107,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.609405,0.000000,0.0,0.0,0.0,0.525581,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.593625,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.600282,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.602928,0.0,0.000000,0.525490,0.00000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.707107,0.0,0.0,0.707107,0.0
4,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.606904,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.525423,0.59632,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0

In [12]:
# Tokenize cleaned text by simple whitespace splitting
df["tokens"] = df["clean_text"].apply(lambda x: x.split())

# Preview tokenized text
df[["clean_text", "tokens"]].head()

,clean_text,tokens
0,grocery urban nestle beverages 1002 beverages nestle premium,"[grocery, urban, nestle, beverages, 1002, beverages, nestle, premium]"
1,home rural tupperware decor 1014 decor tupperware budget flash sale,"[home, rural, tupperware, decor, 1014, decor, tupperware, budget, flash, sale]"
2,electronics urban sony computers 1015 computers sony mid,"[electronics, urban, sony, computers, 1015, computers, sony, mid]"
3,grocery urban nestle spices 1012 spices nestle premium flash sale,"[grocery, urban, nestle, spices, 1012, spices, nestle, premium, flash, sale]"
4,grocery urban tata spices 1016 spices tata premium,"[grocery, urban, tata, spices, 1016, spices, tata, premium]"

# 3. Word2Vec

## Concept

Word2Vec converts words into **dense numerical embeddings**.

Unlike BoW and TF-IDF, Word2Vec can capture some degree of **semantic similarity** between words.

It learns word representations by examining surrounding words in context.

Two common architectures are:
- **CBOW**: predicts a word from surrounding words
- **Skip-Gram**: predicts surrounding words from a given word

## Why We Are Using It

Word2Vec provides:
- dense low-dimensional vectors
- better semantic representation than frequency-based methods

## Limitation

Word2Vec is **context-independent**, meaning a word gets the same embedding everywhere.

For this dataset, Word2Vec is exploratory because the text fields are short business labels rather than full sentences.

In [13]:
# Train a simple Word2Vec model on tokenized text
# vector_size = embedding dimension
# window = context window size
# min_count = minimum frequency required for a word to be learned
# workers = number of CPU cores used
w2v_model = Word2Vec(
    sentences=df["tokens"],
    vector_size=50,
    window=3,
    min_count=1,
    workers=4,
    sg=1  # sg=1 means Skip-Gram
)

print("Word2Vec vocabulary size:", len(w2v_model.wv.index_to_key))
print("Sample words:", w2v_model.wv.index_to_key[:10])

Word2Vec vocabulary size: 96
Sample words: ['urban', 'rural', 'premium', 'mid', 'budget', 'grocery', 'beauty', 'home', 'electronics', 'computers']

## Create Document-Level Word2Vec Vectors

Word2Vec learns vectors for individual words, but our machine learning model later needs **one vector per row**.

So we compute the **average of all word vectors in each row**.

### Formula

For a document with $n$ words:

$
\text{Document Vector} = \frac{1}{n}\sum_{i=1}^{n} \vec{w_i}
$

where:
- $\vec{w_i}$ = embedding of word $i$

In [14]:
# Function to average word vectors for one document
def average_word2vec(tokens, model, vector_size):
    """
    Return the average Word2Vec embedding for a list of tokens.
    If no token is found, return a zero vector.
    """
    valid_vectors = [model.wv[word] for word in tokens if word in model.wv]

    if len(valid_vectors) == 0:
        return np.zeros(vector_size)

    return np.mean(valid_vectors, axis=0)

# Apply function row by row
w2v_vectors = np.array([
    average_word2vec(tokens, w2v_model, 50)
    for tokens in df["tokens"]
])

# Convert to DataFrame
w2v_df = pd.DataFrame(w2v_vectors, columns=[f"w2v_{i}" for i in range(50)])

print("Word2Vec document matrix shape:", w2v_df.shape)
w2v_df.head()

Word2Vec document matrix shape: (2000, 50)

,w2v_0,w2v_1,w2v_2,w2v_3,w2v_4,w2v_5,w2v_6,w2v_7,w2v_8,w2v_9,w2v_10,w2v_11,w2v_12,w2v_13,w2v_14,w2v_15,w2v_16,w2v_17,w2v_18,w2v_19,w2v_20,w2v_21,w2v_22,w2v_23,w2v_24,w2v_25,w2v_26,w2v_27,w2v_28,w2v_29,w2v_30,w2v_31,w2v_32,w2v_33,w2v_34,w2v_35,w2v_36,w2v_37,w2v_38,w2v_39,w2v_40,w2v_41,w2v_42,w2v_43,w2v_44,w2v_45,w2v_46,w2v_47,w2v_48,w2v_49
0,-0.092853,-0.078781,0.060864,0.057939,-0.145222,-0.038916,0.234718,0.117449,-0.239555,-0.066501,0.099180,-0.486961,0.201814,0.217943,-0.061744,0.153571,0.020941,0.041446,-0.172649,-0.166352,0.179930,0.324708,0.472049,-0.191222,0.081422,0.286348,-0.020276,0.118110,-0.193459,-0.030070,-0.177700,-0.481767,0.113250,-0.099940,-0.183477,0.242776,0.037340,0.047396,-0.103322,0.171193,0.238214,-0.003670,-0.169366,0.056596,0.307203,0.110787,0.018722,-0.231596,0.158131,0.148000
1,-0.049718,0.114319,0.163936,0.089554,-0.152529,0.139797,0.194684,0.526750,-0.042830,-0.169253,0.020874,-0.239007,0.232380,0.268796,-0.214699,-0.022034,0.152720,0.147543,-0.221057,-0.116703,0.148645,0.073457,0.554717,0.066154,0.243456,0.237691,-0.176621,0.427574,-0.206159,0.272440,-0.029912,-0.316144,0.123420,-0.126635,-0.073913,-0.051376,0.040172,0.046355,0.011149,0.119348,0.205388,-0.127950,-0.147774,-0.053626,0.168481,-0.272325,0.280231,-0.438868,-0.040024,0.031182
2,0.009395,0.186711,-0.116326,0.156620,0.175861,-0.239864,0.126047,0.136162,-0.130366,-0.132628,0.005319,-0.303921,0.138961,0.216313,-0.297463,0.021461,0.188965,0.185597,-0.179694,-0.099145,0.242254,0.363535,0.295761,-0.124858,0.069699,-0.008700,-0.097466,0.293911,-0.119754,-0.036777,-0.302990,-0.436356,0.195697,-0.104784,-0.276510,-0.032093,0.301736,0.296987,-0.145000,0.382843,0.319254,-0.188566,-0.095436,0.094580,0.434392,-0.157939,-0.003357,0.005053,0.244950,0.208609
3,-0.068717,-0.054978,0.119850,0.099447,-0.184870,-0.033369,0.247362,0.115194,-0.242147,-0.060342,0.094890,-0.436076,0.217028,0.190267,-0.066548,0.112078,0.033448,0.119414,-0.191920,-0.161345,0.167535,0.301401,0.482220,-0.168005,0.104268,0.261429,-0.048881,0.149484,-0.183948,0.022975,-0.108778,-0.419149,0.107424,-0.133682,-0.183206,0.161866,-0.005574,0.069364,-0.037646,0.161575,0.251661,0.008420,-0.165129,0.026597,0.317120,0.072661,0.051147,-0.265374,0.153415,0.083529
4,-0.112688,-0.091370,0.139225,0.101014,-0.277112,-0.042811,0.325036,0.018364,-0.257448,-0.022257,0.153748,-0.505112,0.260903,0.168787,-0.023511,0.158331,-0.023104,0.096796,-0.223699,-0.199262,0.129675,0.345709,0.538197,-0.164134,0.106573,0.265167,-0.003282,0.083166,-0.222334,-0.009097,-0.073188,-0.464700,0.097350,-0.196498,-0.230481,0.167753,-0.045638,0.077580,-0.026506,0.134925,0.273397,0.080816,-0.219793,-0.023117,0.365533,0.151120,-0.015934,-0.214387,0.232822,0.072761

## Observation

Word2Vec learned a vocabulary of **96 unique tokens** and produced a **2000 × 50** dense document embedding matrix after averaging word vectors row by row.

The sample vocabulary includes meaningful business words such as:
- `urban`, `rural`
- `premium`, `mid`, `budget`
- `grocery`, `beauty`, `home`, `electronics`
- `computers`

This indicates that Word2Vec is capturing semantic relationships among store, product, and brand-related terms rather than only raw counts. However, because each row contains only short label-style text instead of full natural-language sentences, the learned semantic context is limited. As a result, Word2Vec provides a compact dense representation, but its benefit in this dataset is still exploratory rather than strongly language-driven.

# 4. BERT / Transformer Embeddings

## Concept

BERT-based embeddings produce **context-aware vector representations**.

Unlike Word2Vec, BERT can generate embeddings that reflect the context in which words appear.

For this notebook, we use a lightweight sentence-transformer model to generate one embedding per row.

## Why We Are Using It

Transformer embeddings provide:
- richer semantic representation
- context-aware text encoding
- strong performance in modern NLP tasks

## Limitation

They are more computationally expensive than BoW, TF-IDF, or Word2Vec.

In this dataset, BERT is exploratory because the text fields are short labels and not long natural-language sentences.

In [15]:
# Load a lightweight sentence transformer model
bert_model = SentenceTransformer("all-MiniLM-L6-v2")

# Generate embeddings for each text row
bert_vectors = bert_model.encode(
    df["clean_text"].tolist(),
    show_progress_bar=True
)

# Convert embeddings to DataFrame
bert_df = pd.DataFrame(
    bert_vectors,
    columns=[f"bert_{i}" for i in range(bert_vectors.shape[1])]
)

print("BERT embedding matrix shape:", bert_df.shape)
bert_df.head()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/63 [00:00<?, ?it/s]

BERT embedding matrix shape: (2000, 384)

,bert_0,bert_1,bert_2,bert_3,bert_4,bert_5,bert_6,bert_7,bert_8,bert_9,bert_10,bert_11,bert_12,bert_13,bert_14,bert_15,bert_16,bert_17,bert_18,bert_19,bert_20,bert_21,bert_22,bert_23,bert_24,bert_25,bert_26,bert_27,bert_28,bert_29,bert_30,bert_31,bert_32,bert_33,bert_34,bert_35,bert_36,bert_37,bert_38,bert_39,bert_40,bert_41,bert_42,bert_43,bert_44,bert_45,bert_46,bert_47,bert_48,bert_49,bert_50,bert_51,bert_52,bert_53,bert_54,bert_55,bert_56,bert_57,bert_58,bert_59,bert_60,bert_61,bert_62,bert_63,bert_64,bert_65,bert_66,bert_67,bert_68,bert_69,bert_70,bert_71,bert_72,bert_73,bert_74,bert_75,bert_76,bert_77,bert_78,bert_79,bert_80,bert_81,bert_82,bert_83,bert_84,bert_85,bert_86,bert_87,bert_88,bert_89,bert_90,bert_91,bert_92,bert_93,bert_94,bert_95,bert_96,bert_97,bert_98,bert_99,bert_100,bert_101,bert_102,bert_103,bert_104,bert_105,bert_106,bert_107,bert_108,bert_109,bert_110,bert_111,bert_112,bert_113,bert_114,bert_115,bert_116,bert_117,bert_118,bert_119,bert_120,bert_121,bert_122,bert_123,bert_124,bert_125,bert_126,bert_127,bert_128,bert_129,bert_130,bert_131,bert_132,bert_133,bert_134,bert_135,bert_136,bert_137,bert_138,bert_139,bert_140,bert_141,bert_142,bert_143,bert_144,bert_145,bert_146,bert_147,bert_148,bert_149,bert_150,bert_151,bert_152,bert_153,bert_154,bert_155,bert_156,bert_157,bert_158,bert_159,bert_160,bert_161,bert_162,bert_163,bert_164,bert_165,bert_166,bert_167,bert_168,bert_169,bert_170,bert_171,bert_172,bert_173,bert_174,bert_175,bert_176,bert_177,bert_178,bert_179,bert_180,bert_181,bert_182,bert_183,bert_184,bert_185,bert_186,bert_187,bert_188,bert_189,bert_190,bert_191,bert_192,bert_193,bert_194,bert_195,bert_196,bert_197,bert_198,bert_199,bert_200,bert_201,bert_202,bert_203,bert_204,bert_205,bert_206,bert_207,bert_208,bert_209,bert_210,bert_211,bert_212,bert_213,bert_214,bert_215,bert_216,bert_217,bert_218,bert_219,bert_220,bert_221,bert_222,bert_223,bert_224,bert_225,bert_226,bert_227,bert_228,bert_229,bert_230,bert_231,bert_232,bert_233,bert_234,bert_235,bert_236,bert_237,bert_238,bert_239,bert_240,bert_241,bert_242,bert_243,bert_244,bert_245,bert_246,bert_247,bert_248,bert_249,bert_250,bert_251,bert_252,bert_253,bert_254,bert_255,bert_256,bert_257,bert_258,bert_259,bert_260,bert_261,bert_262,bert_263,bert_264,bert_265,bert_266,bert_267,bert_268,bert_269,bert_270,bert_271,bert_272,bert_273,bert_274,bert_275,bert_276,bert_277,bert_278,bert_279,bert_280,bert_281,bert_282,bert_283,bert_284,bert_285,bert_286,bert_287,bert_288,bert_289,bert_290,bert_291,bert_292,bert_293,bert_294,bert_295,bert_296,bert_297,bert_298,bert_299,bert_300,bert_301,bert_302,bert_303,bert_304,bert_305,bert_306,bert_307,bert_308,bert_309,bert_310,bert_311,bert_312,bert_313,bert_314,bert_315,bert_316,bert_317,bert_318,bert_319,bert_320,bert_321,bert_322,bert_323,bert_324,bert_325,bert_326,bert_327,bert_328,bert_329,bert_330,bert_331,bert_332,bert_333,bert_334,bert_335,bert_336,bert_337,bert_338,bert_339,bert_340,bert_341,bert_342,bert_343,bert_344,bert_345,bert_346,bert_347,bert_348,bert_349,bert_350,bert_351,bert_352,bert_353,bert_354,bert_355,bert_356,bert_357,bert_358,bert_359,bert_360,bert_361,bert_362,bert_363,bert_364,bert_365,bert_366,bert_367,bert_368,bert_369,bert_370,bert_371,bert_372,bert_373,bert_374,bert_375,bert_376,bert_377,bert_378,bert_379,bert_380,bert_381,bert_382,bert_383
0,0.019519,0.035894,0.006501,0.005474,0.032532,0.009000,-0.032032,0.010910,-0.001356,-0.006492,-0.007242,-0.069013,-0.059507,-0.016442,0.036766,-0.038140,0.009790,-0.029988,0.021914,-0.093959,-0.010006,-0.072440,0.035189,0.006244,0.033071,0.092676,0.016329,0.058809,-0.013505,-0.024259,0.062140,0.045098,0.073857,-0.013253,0.001952,-0.027706,0.068708,-0.094382,0.014232,-0.036728,0.103842,-0.042366,-0.029061,-0.011378,-0.021398,-0.001483,-0.095435,0.106851,0.022592,0.022983,-0.091872,-0.011558,0.020245,-0.039998,0.005176,0.003343,-0.025824,-0.025057,0.040420,0.045489,0.015363,-0.010060,-0.088033,0.011045,-0.050195,0.009212,-0.081680,0.058867,0.002887,-0.028521,0.017522,-0.038840,0.067562,-0.028332,0.045048,-0.010523,0.062950,-0.033539,-0.007633,-0.005679,-0.063551,-0.044360,-0.007301,0.012394,-0.037044,-0.112148,0.024088,-0.020981,-0.012486,-0.030929,-0.035623,-0.034198,-0.019385,0.007621,-0.056302,0.020313,-0.042570,-0.091425,-0.019161,0.027365,-0.052468,-0.025684,0.032527,-0.044688,0.016921,-0.090673,0.047859,0.033005,0.109875,0.062052,-0.079659,-0.010010,0.012897,0.019063,-0.057027,-0.075992,0.009739,-0.027747,0.106002,0.007221,-0.014059,0.041841,0.047043,-0.036348,-0.043704,0.004977,0.013105,3.527225e-33,-0.071230,-0.050849,0.075808,0.077234,0.094088,-0.042347,-0.019492,-0.017827,0.046656,-0.006521,-0.015389,-0.025500,-0.066418,0.072340,0.035818,-0.085708,-0.026512,0.030221,-0.002550,0.000451,-0.162454,-0.049680,-0.007627,0.048784,0.031032,0.028111,0.061691,-0.044938,0.109860,0.060296,0.074466,0.021254,0.018484,-0.029448,-0.084690,0.103313,0.006861,-0.055380,-0.001033,0.024306,-0.034088,-0.027143,0.103656,0.019425,-0.075331,-0.007882,0.008849,0.014753,-0.023489,0.003919,-0.026509,-0.041064,-0.115176,0.066351,-0.088803,-0.016496,-0.054276,0.042002,0.055086,-0.026650,0.007393,0.061808,-0.031103,-0.042467,-0.024276,-0.007704,-0.060358,-0.093271,-0.000471,0.049845,0.008695,0.040590,0.051062,-0.013287,0.028850,0.042682,0.125873,0.069160,0.082071,0.006453,0.002994,-0.031493,0.063042,0.084027,-0.016891,-0.007313,-0.039621,-0.014992,0.084297,0.060148,-0.058605,-0.037468,-0.002213,-0.001215,0.023409,-4.812254e-33,0.029525,-0.037013,0.017127,0.012828,0.047697,-0.003796,0.024938,-0.006709,0.020246,-0.083435,-0.015204,0.024808,0.098488,0.018287,-0.042889,0.065626,0.070282,0.007664,0.029701,-0.021648,-0.006219,0.056549,0.027914,0.047665,0.037279,-0.016838,-0.028314,0.081487,-0.030078,-0.012656,0.058406,-0.035604,0.019573,0.031103,0.022727,-0.038132,0.014757,-0.060225,0.011697,-0.008141,0.062079,-0.067373,-0.054589,0.006482,0.095109,-0.003079,0.051173,-0.154033,-0.004883,-0.019132,-0.021231,-0.020112,-0.123605,0.084474,-0.090447,0.038831,0.015995,0.001839,0.003491,-0.096742,-0.017591,0.130820,-0.005497,-0.025736,0.051048,-0.063287,-0.046485,-0.052746,0.039590,-0.094214,0.004355,0.007639,-0.022573,-0.023157,-0.103657,0.043253,-0.014953,0.008687,-0.009145,-0.050419,0.002299,0.003272,-0.061878,0.050657,0.042746,-0.034106,0.120973,0.047657,-0.023262,0.100732,-0.024290,0.049177,-0.068301,0.094088,0.048970,-2.112561e-08,0.025385,0.005247,-0.030116,0.127841,0.006105,-0.026346,-0.020977,0.019729,-0.033390,0.014653,-0.042134,0.016846,-0.105937,-0.025485,-0.052521,-0.004193,-0.038428,0.038557,0.002094,0.091865,-0.039682,0.049949,0.059897,0.042318,-0.081632,-0.016750,0.052486,-0.056129,0.047453,-0.064532,0.017595,0.130339,-0.048222,0.088657,-0.029417,-0.023029,-0.035063,0.050608,-0.060751,-0.017850,0.020770,-0.150745,-0.093215,-0.056098,-0.037210,0.038044,-0.073301,0.028019,-0.017111,0.047369,0.011064,0.072556,0.022364,0.028537,0.006231,0.003559,-0.041256,-0.061348,0.030572,-0.047783,0.059716,-0.022520,0.009461,0.014864
1,-0.027409,0.005514,-0.001803,-0.005229,0.057841,-0.036739,-0.042057,-0.031624,-0.123422,-0.010395,0.020976,-0.030858,-0.002289,0.008946,0.045246,-0.041564,0.049168,-0.004511,0.099433,-0.063342,-0.052337,-0.000157,-0.010870,-0.037321,0.027823,-0.005746,0.020606,0.047834,-0.100756,-0.095247,0.026293,0.033491,-0.052442,0.028083,0.106954,0.037942,-0.009856,-0.022116,0.057068,0.040328,0.020091,-0.102571,0.049917,-0.035024,0.011733,-0.013387,-0.045025,0.051949,0.022474,-0.029299,0.018844,0.042260,-0.050686,-0.006266,0.036203,0.023983,-0.043531,-0.094131,0.018287,-0.019340,0.073468,-0.001605,-0.064095,-0.011007,-0.048183,-0.025967,-0.042534,0.060199,0.007646,-0.042841,0.055345,0.030972,0.001914,0.042250,0.045490,-0.092400,0.080726,-0.019021,-0.072105,0.016773,-0.043924,-0.005217,-0.003584,-0.002524,-0.024311,0.008679,0.007112,-0.021457,0.036334,0.025514,-0.013470,0.023713,0.000746,-0.069286,-0.138036,-0.075405,-0.015399,-0.073309,-0.018040,0.060500,-0.052574,-0.075438,0.078511,-0.028764,0.012582,-0.079074,0.052241,0.063331,0.006626,0.027042,-0.016280,-0.022810,-0.083197,-0.040355,-0.041925,-0.116449,-0.033881,-0.070988,0.091518,-0.028854,0.070560,0.050094,0.012456,-0.082098,0.048931,0.006551,0.030183,7.265119e-33,-0.041107,0.085840,-0.053755,0.070969,0.109341,0.038080,0.065218,-0.022353,-0.004154,0.052680,0.003455,0.003129,-0.073402,0.051540,0.039150,-0.013505,-0.020663,0.018342,0.020288,-0.076003,-0.090532,0.033285,-0.028336,0.075681,-0.083354,-0.050729,-0.005948,-0.016740,0.062726,0.064682,0.136010,0.021555,0.102418,-0.038543,-0.039746,-0.023050,-0.051090,-0.121944,0.019150,0.014720,-0.069664,0.047087,-0.012284,0.030936,-0.054252,0.032658,0.084256,0.063104,0.030625,0.037858,0.030096,-0.016191,-0.030075,0.037149,-0.035265,-0.048657,0.004393,-0.043805,0.054248,-0.025283,0.082664,0.044913,-0.025551,-0.124959,-0.019383,-0.062420,0.133123,-0.019895,0.049383,-0.011393,0.023595,-0.006821,0.013789,-0.033780,0.086907,-0.004435,0.003964,0.014483,0.006322,-0.022414,0.023364,-0.055400,0.017981,0.034830,0.011061,-0.036211,0.035539,0.015470,0.008701,0.036136,0.062358,0.014170,-0.001882,-0.058923,0.012787,-6.059726e-33,-0.013690,-0.023563,-0.089042,0.102952,0.019827,0.026452,-0.037287,0.002669,0.066176,0.021728,-0.061817,0.040644,-0.014138,-0.033196,-0.012688,-0.010079,0.035699,0.006691,0.055784,-0.049049,-0.062912,0.020635,-0.039883,-0.005188,-0.033675,0.102422,-0.066863,0.073401,-0.048112,-0.029900,-0.046349,-0.117753,0.052856,0.112819,-0.033996,-0.005113,0.030251,0.011602,-0.040849,-0.000369,0.083083,-0.042577,0.038656,0.037808,-0.061162,-0.101517,-0.080710,-0.013111,0.034300,0.008454,0.016855,0.081538,-0.035276,-0.056557,-0.108998,0.048169,0.060747,0.013022,0.025611,0.061434,0.040546,0.052700,-0.037367,0.112829,0.084809,0.020927,0.081030,-0.016332,-0.064720,-0.007728,-0.033316,0.065030,0.030418,-0.115176,-0.043118,0.020525,0.053465,0.091045,0.069501,0.023514,-0.030837,-0.036266,-0.000644,0.021119,-0.026154,-0.064612,0.050123,0.039120,0.004346,0.046807,-0.066767,0.084206,0.085955,0.044272,0.060036,-2.436469e-08,0.050502,0.035846,-0.027274,0.001665,0.046887,0.029447,0.032815,0.030822,-0.011112,-0.018394,-0.015186,0.028480,-0.014725,0.040635,0.006152,0.004464,0.003664,-0.010664,-0.062067,-0.016795,0.022297,0.041672,-0.005867,-0.043927,-0.098430,0.075305,-0.026730,0.077991,0.061051,0.005591,0.003190,-0.020052,-0.019282,0.024166,-0.011546,-0.067592,-0.128577,-0.016947,-0.056565,0.007858,-0.021922,-0.076914,-0.087577,-0.014213,0.007536,0.032621,-0.052285,-0.065585,-0.047947,0.082505,-0.102528,-0.050013,-0.029286,0.004295,-0.018400,-0.031656,0.017239,-0.035729,0.020298,0.042037,-0.036308,0.017322,-0.044272,0.113899
2,0.003602,0.013918,0.018764,-0.133172,0.025483,0.002544,-0.014594,0.069418,-0.015907,0.083045,0.056530,0.021794,0.014636,0.005392,0.016711,0.090147,-0.047171,-0.009783,0.053449,-0.021327,0.000572,-0.116121,-0.044190,-0.002762,0.003322,0.075636,0.072663,0.050929,-0.075297,-0.009575,-0.111588,0.038640,0.084293,0.053437,-0.015907,-0.055737,0.036666,0.003814,-0.008623,-0.039773,-0.011087,-0.019675,0.012640,0.011093,0.032211,-0.007606,-0.050926,-0.001916,0.073048,-0.031871,-0.012642,0.014305,0.010438,0.006984,-0.110045,-0.050344,0.014906,0.069964,0.013091,0.002304,0.039158,-0.063978,-0.017281,0.035154,0.004955,0.001843,0.021193,0.002450,-0.010435,-0.087533,-0.063780,-0.018272,0.003351,0.046989,-0.022662,-0.020896,0.019442,-0.031705,-0.011247,-0.018125,-0.064258,-0.066852,-0.163697,0.009248,0.021175,0.068383,-0.046475,0.022047,-0.019002,-0.122274,-0.093076,-0.030818,-0.028855,-0.006508,-0.094500,-0.048707,0.023320,-0.046099,-0.054637,0.065830,0.001496,0.018407,0.053180,-0.064249,-0.120814,-0.065792,0.004681,0.056460,-0.007653,-0.071521,-0.102902,0.032172,-0.062502,-0.053909,0.050281,-0.031935,-0.061651,0.049304,0.026100,-0.102689,-0.059035,-0.096478,-0.062536,0.002677,0.015013,-0.062569,0.019097,4.162396e-33,0.014908,0.042470,-0.043497,0.026170,-0.084539,0.033004,0.063236,0.097057,-0.026195,0.004225,0.050068,-0.009627,0.002842,-0.028895,0.038158,-0.015672,0.071773,-0.058535,-0.004296,-0.023803,-0.007924,0.032925,0.015785,0.010113,0.072255,0.076672,-0.039637,-0.007101,0.126167,0.037527,0.011919,0.025955,-0.028341,-0.044099,-0.002060,0.068114,-0.042980,0.028715,0.042081,-0.005080,0.009711,0.083127,-0.042103,-0.024773,0.043052,0.010936,-0.002025,0.109497,0.003355,0.006463,-0.072537,0.043319,-0.037213,0.048756,0.041763,-0.024022,0.021671,0.036979,0.013460,0.105584,0.151740,0.056437,-0.083712,-0.023565,-0.043874,0.063984,0.100304,-0.019789,0.087718,0.044547,0.023046,-0.073590,0.032889,0.060495,-0.021011,0.045551,-0.093692,-0.055157,-0.067889,0.016243,-0.078864,-0.020416,-0.008581,0.082908,0.025750,0.060854,-0.017436,-0.047650,-0.084054,-0.022947,0.069853,0.002518,0.052971,0.081834,-0.080551,-3.502997e-33,0.018092,-0.047463,-0.044533,-0.013354,-0.058631,-0.038020,0.018550,0.024811,-0.020900,-0.024717,0.030662,-0.047484,-0.015233,-0.031085,0.030049,-0.006142,0.062380,0.010881,0.056514,0.003984,0.102038,0.107372,0.028611,-0.054396,0.007062,0.028977,0.015322,0.073188,-0.005834,0.056170,0.033280,-0.052024,-0.004588,0.047782,0.005688,-0.057843,0.033180,-0.024917,0.011765,-0.056498,0.066654,0.061009,-0.089764,0.033978,-0.013596,-0.030777,-0.052750,0.022789,0.072880,-0.036328,0.042320,-0.079207,0.025328,-0.037531,0.027280,0.015496,-0.051068,0.053404,0.069689,-0.096680,0.048008,-0.049601,-0.023747,-0.032962,-0.057734,0.068109,0.135891,0.069586,-0.028759,-0.042097,-0.029597,0.046842,0.056672,0.015468,-0.030433,0.028448,-0.101123,0.021495,0.052515,0.008509,-0.067807,-0.021772,-0.048921,0.069262,-0.013890,0.048571,-0.003672,-0.029315,0.020146,-0.038177,-0.038735,0.064414,0.043814,0.041106,-0.086014,-1.822829e-08,0.104634,-0.065324,-0.009719,0.017121,0.027413,-0.052760,-0.006787,0.028869,0.077086,0.000513,0.051420,0.012927,0.006244,0.078806,0.038330,0.022363,0.022760,0.011893,-0.019918,-0.017250,0.039722,-0.025829,0.020532,0.006841,0.111211,-0.047248,-0.066600,-0.025130,0.032158,-0.022697,-0.030295,-0.040948,0.012651,-0.030073,0.057202,0.026704,-0.008977,0.019662,-0.020070,-0.067813,0.054350,-0.133934,-0.041859,0.031754,0.062658,-0.111023,-0.002798,-0.058142,-0.046346,-0.022387,-0.039604,0.052302,0.004742,-0.016066,-0.003793,-0.081107,0.010227,0.013790,-0.030520,0.061409,0.016869,0.044888,-0.006296,0.023414
3,-0.064240,0.009937,0.008962,0.042035,0.023387,0.032920,-0.056224,0.003501,0.030361,-0.052599,0.090758,-0.041887,-0.027221,-0.041692,0.045534,-0.035948,0.009331,0.033080,-0.002583,-0.109840,-0.044651,-0.043074,0.032568,-0.039835,-0.011370,0.069053,-0.015088,0.062649,-0.030045,-0.074268,0.093332,0.046094,0.026580,0.035991,0.010766,-0.060208,0.029081,-0.061869,0.079597,0.040314,0.071588,-0.093492,-0.030537,-0.038877,0.002020,-0.010624,-0.035012,0.090159,0.052360,-0.013057,-0.066538,0.046032,-0.062469,0.014370,-0.020580,0.040565,-0.063547,-0.047264,0.031226,0.015846,0.032175,-0.037572,-0.039775,-0.012521,-0.079858,0.005325,-0.085528,0.063850,0.055129,-0.047721,0.010356,-0.037162,0.010411,0.040150,0.048168,-0.005832,0.051718,-0.089237,-0.027782,-0.046930,-0.012360,-0.072734,-0.052664,-0.021782,-0.020116,-0.046720,0.035928,-0.006130,0.041167,-0.019197,-0.014192,-0.030841,-0.060936,0.033358,-0.117690,0.034937,0.015112,-0.060692,-0.090378,0.069239,-0.058153,-0.068989,0.005574,-0.033938,-0.044106,-0.061187,0.033766,0.005446,0.044636,0.031720,-0.093503,0.047848,-0.094647,-0.073288,-0.028789,-0.100142,0.020227,-0.016631,0.061787,0.000528,0.068511,0.032483,-0.016203,-0.031693,-0.040786,0.000639,0.008632,6.333159e-33,-0.095127,0.008927,0.017359,0.062156,0.078311,-0.009646,0.025979,-0.042075,0.015140,0.054243,-0.037141,0.024084,-0.121367,0.071823,0.032579,-0.060306,0.010383,0.006810,0.025085,-0.094668,-0.117406,0.041076,-0.019215,0.051428,-0.002017,0.047722,0.054564,-0.020990,0.124488,0.058842,0.063988,-0.011208,0.030801,-0.034644,-0.077639,0.065549,-0.038592,-0.117874,0.038912,-0.013633,-0.071634,0.000329,-0.000537,0.042217,-0.080211,0.039119,0.011089,0.063607,0.085754,0.029752,-0.013244,-0.032454,-0.044507,0.077038,-0.051972,0.007043,-0.072007,0.001445,0.050517,-0.011264,0.053643,0.046230,0.024983,-0.045697,-0.029421,-0.045103,-0.047237,-0.069323,0.024196,0.105105,0.007655,0.047531,0.062413,-0.019660,0.068497,0.024985,0.077825,0.050412,0.080513,-0.034833,0.024219,-0.037875,0.070909,0.157990,-0.007268,0.000689,-0.035910,-0.005589,0.074068,0.025485,-0.017221,-0.007098,0.045145,-0.022178,0.002692,-6.325185e-33,0.025076,0.009347,-0.046075,0.062108,0.031191,0.079402,-0.046732,-0.035102,0.022933,0.024523,-0.069189,-0.020378,0.080898,-0.087719,-0.013148,0.043310,0.081260,0.053160,0.040305,-0.002741,-0.011344,0.067896,-0.061829,0.041931,-0.026587,0.003417,-0.002579,0.120502,-0.066567,-0.022938,0.095485,-0.049143,0.035752,0.049531,0.024086,0.033460,0.054508,-0.058278,-0.010817,-0.032836,0.025830,-0.036003,-0.005766,0.025824,0.009008,-0.038571,0.050814,-0.051737,0.084740,-0.003402,-0.023448,0.039281,-0.106677,0.026886,-0.117335,0.048498,0.026010,0.007949,0.051206,-0.044434,-0.006328,0.075703,-0.031908,-0.032570,0.080668,-0.049308,0.032696,-0.075647,0.003167,-0.045268,0.078130,0.038221,-0.032190,-0.080073,-0.048076,0.054582,0.000944,-0.006441,-0.013623,-0.015226,0.043204,-0.063433,-0.033493,0.050986,-0.042075,-0.000213,0.040086,0.126034,0.067385,0.052527,-0.015433,0.066835,-0.006332,0.042203,0.077832,-2.369856e-08,0.032281,0.023047,0.011553,0.058924,0.037497,0.022052,-0.009510,0.036769,0.007576,0.009321,-0.038100,0.027037,-0.096724,0.007563,-0.071038,0.007358,-0.037263,0.039776,-0.015998,0.050026,-0.017263,0.072274,0.043818,-0.067668,-0.009689,-0.026221,0.037776,0.041242,0.049235,-0.009613,0.079722,0.012437,0.003792,0.036188,-0.059180,-0.038308,-0.072713,0.052914,-0.085965,-0.017844,-0.023822,-0.127441,-0.052208,-0.000825,-0.093677,0.029322,-0.081563,-0.037625,-0.026572,0.013728,-0.057799,-0.027025,-0.002103,-0.034079,-0.051548,-0.019144,-0.049071,-0.003775,0.065777,-0.057439,0.025524,-0.026008,-0.095718,0.067426

## Observation

BERT produced a **2000 × 384** embedding matrix, which is the richest and highest-dimensional representation among the four methods tested.

This method generates contextual sentence-level embeddings, so each row is represented by a dense vector rather than a sparse count table. In theory, this is more expressive than BoW, TF-IDF, or Word2Vec.

However, in this dataset the input text is still composed mostly of short business labels such as category names, brand names, product labels, promotion types, and identifiers. Because the rows are not long natural-language descriptions, BERT's contextual advantage is present but likely underutilized. Therefore, BERT provides the most advanced representation technically, but its practical gain for this structured retail dataset may be limited.

# Compare the Four Vectorization Outputs

This section compares the dimensionality of the four vectorization methods.

In [16]:
# Compare the shape of all vector outputs
comparison_df = pd.DataFrame({
    "Method": ["Bag of Words", "TF-IDF", "Word2Vec", "BERT"],
    "Rows": [
        bow_df.shape[0],
        tfidf_df.shape[0],
        w2v_df.shape[0],
        bert_df.shape[0]
    ],
    "Columns / Features": [
        bow_df.shape[1],
        tfidf_df.shape[1],
        w2v_df.shape[1],
        bert_df.shape[1]
    ]
})

comparison_df

         Method  Rows  Columns / Features
0  Bag of Words  2000                  95
1        TF-IDF  2000                  95
2      Word2Vec  2000                  50
3          BERT  2000                 384

# Summary and Interpretation

The four vectorization methods were implemented successfully on the text-like fields of the updated retail dataset.

## Summary of Methods

- **Bag of Words (BoW)**  
  Produced a **2000 × 95** sparse matrix based on token counts.

- **TF-IDF**  
  Produced a **2000 × 95** weighted matrix that emphasizes more distinctive terms.

- **Word2Vec**  
  Learned a **96-token vocabulary** and generated a **2000 × 50** dense embedding matrix.

- **BERT / Transformer Embeddings**  
  Produced a **2000 × 384** contextual embedding matrix.

## Overall Interpretation

The results confirm that these methods can be applied successfully to the selected text-like fields. However, the underlying text in this dataset is mostly composed of:

- short categorical labels
- brand and product names
- promotion labels
- numeric identifiers

rather than long natural-language text.

As a result:

- **BoW** and **TF-IDF** mainly capture token presence and relative importance
- **Word2Vec** captures limited semantic similarity among business terms
- **BERT** provides the richest representation, but its contextual power is not fully utilized in short label-based records

## Practical Conclusion

These vectorization methods satisfy the project requirement and are useful for comparative analysis. However, for this retail dataset, they should be treated as **secondary / exploratory text representations** rather than the primary feature engineering strategy.

More suitable methods for the full forecasting pipeline are likely to be:

- categorical encoding
- date and calendar feature extraction
- lag features
- rolling statistics
- price-promotion interaction features
- store/product aggregation features

## Optional Step: Save Vectorized Outputs

If needed, the generated feature matrices can be saved for use in later machine learning experiments.

In [17]:
# Save vectorized outputs as CSV files for later use
bow_df.to_csv("bow_features.csv", index=False)
tfidf_df.to_csv("tfidf_features.csv", index=False)
w2v_df.to_csv("word2vec_features.csv", index=False)
bert_df.to_csv("bert_features.csv", index=False)

print("Feature files saved successfully.")

Feature files saved successfully.

## Final Conclusion

The four vectorization methods were applied successfully to the text-like fields of the updated retail dataset.

From the actual outputs:
- **BoW** and **TF-IDF** each produced **95 features**
- **Word2Vec** produced **50 dense features**
- **BERT** produced **384 dense contextual features**

These results show that the text-like fields can be transformed into machine-readable vectors. However, since the dataset is primarily structured and categorical rather than text-heavy, these methods are best viewed as exploratory approaches for this project.

For the broader retail demand forecasting task, more suitable feature engineering methods will include categorical encoding, calendar-based features, lag variables, rolling statistics, interaction variables, and aggregation-based features.

# Summary and Interpretation

The text-like fields of the updated retail dataset were explored using four vectorization methods:

- Bag of Words (BoW)
- TF-IDF
- Word2Vec
- BERT / Transformer Embeddings

In addition, an improved **column-wise TF-IDF** approach was tested to preserve the semantic meaning of individual text-like columns.

## Key Findings

- BoW and TF-IDF on combined text provide baseline vector representations.
- However, combining all text-like fields into one document mixes different business meanings such as product, brand, promotion, and store type.
- Column-wise TF-IDF improves interpretability by preserving feature-specific context.
- Word2Vec and BERT generate dense embeddings, but their value is limited because the dataset does not contain long natural-language text.

## Final Interpretation

Although these vectorization methods were successfully applied, the dataset is fundamentally a **structured categorical retail dataset**, not a text-heavy NLP dataset.

Therefore, the most appropriate techniques for this dataset are still:

- one-hot encoding
- frequency encoding
- target encoding
- business-oriented feature engineering

The vectorization methods are useful as exploratory techniques, but they are not the primary feature engineering strategy for this problem.

## Comparison: Combined TF-IDF vs Column-wise TF-IDF

The two TF-IDF strategies differ in how they treat the text-like columns.

| Approach | Description | Strength | Limitation |
|----------|-------------|----------|------------|
| Combined TF-IDF | All text columns merged into one document per row | Simple baseline | mixes unrelated semantics |
| Column-wise TF-IDF | Each text column vectorized separately | preserves feature meaning better | still less suitable than categorical encoding for this dataset |